const filters = {
  blur: {
    text: "Độ Mờ",
    min: 0,
    max: 10,
    initValue: 0,
    unit: "px",
  },
  brightness: {
    text: "Độ Sáng",
    min: 0,
    max: 200,
    initValue: 100,
    unit: "%",
  },
  contrast: {
    text: "Độ Tương Phản",
    min: 0,
    max: 200,
    initValue: 100,
    unit: "%",
  },
  grayscale: {
    text: "Thang Độ Xám",
    min: 0,
    max: 100,
    initValue: 0,
    unit: "%",
  },
  invert: {
    text: "Đảo Màu",
    min: 0,
    max: 100,
    initValue: 0,
    unit: "%",
  },
  opacity: {
    text: "Độ Trong Suốt",
    min: 0,
    max: 100,
    initValue: 100,
    unit: "%",
  },
  saturate: {
    text: "Độ Bão Hòa",
    min: 0,
    max: 200,
    initValue: 100,
    unit: "%",
  },
  sepia: {
    text: "Hiệu Ứng Sepia",
    min: 0,
    max: 100,
    initValue: 0,
    unit: "%",
  },
  "hue-rotate": {
    text: "Xoay Màu",
    min: 0,
    max: 360,
    initValue: 0,
    unit: "deg",
  },
};
